version: '3.8'

services:
  db:
    image: postgres:16
    container_name: careergenie-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend-node/SQL:/docker-entrypoint-initdb.d/

  minio:
    image: minio/minio:latest
    container_name: careergenie-minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
      MINIO_API_CORS_ALLOW_ORIGIN: "http://localhost:5173,http://127.0.0.1:5173"
    ports:
      - "9000:9000" 
      - "9001:9001" 
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  createbucket:
    image: minio/mc:latest
    container_name: careergenie-minio-setup
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for MinIO to spin up...';
      until (mc alias set myminio http://minio:9000 admin password123); do
        echo '...still waiting for MinIO...';
        sleep 1;
      done;
      echo 'MinIO is up! Provisioning bucket...';
      mc mb myminio/interview-recordings --ignore-existing;
      mc anonymous set private myminio/interview-recordings;
      echo 'Bucket successfully configured. Exiting setup.';
      exit 0;
      "

  node-backend:
    build: ./backend-node
    container_name: careergenie-node
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
    ports:
      - "5000:5000"
    depends_on:
      - db
      - minio
    volumes:
      - ./backend-node:/app
      - /app/node_modules

volumes:
  pgdata:
  minio_data: