ALTER TABLE candidate
ADD COLUMN IF NOT EXISTS photo_data BYTEA,
ADD COLUMN IF NOT EXISTS photo_mime_type TEXT,
ADD COLUMN IF NOT EXISTS photo_filename TEXT,
ADD COLUMN IF NOT EXISTS cv_data BYTEA,
ADD COLUMN IF NOT EXISTS cv_mime_type TEXT,
ADD COLUMN IF NOT EXISTS cv_filename TEXT;